# Generated by Django 5.1 on 2024-11-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='status',
        ),
    ]
