# Generated by Django 5.1 on 2024-11-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_supplier_address_remove_supplier_contact_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
