# Generated by Django 5.1 on 2024-11-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='IMEI',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
