# Generated by Django 5.1 on 2024-11-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sale_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('feature phone', 'feature phone'), ('smart phone', 'smart phone')], max_length=50, null=True),
        ),
    ]
