# Generated by Django 5.1 on 2024-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_purchase_price_purchase_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=50, null=True),
        ),
    ]
