# Generated by Django 5.1 on 2024-11-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_purchase_imei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='IMEI',
            new_name='imei',
        ),
    ]
