# Generated by Django 5.1 on 2024-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_imei_sale_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
