# Generated by Django 5.1 on 2024-11-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sale_status_alter_sale_imei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
    ]
